spring:
  application:
    name: japanese-learning-backend

  datasource:
    url: jdbc:mysql://localhost:3306/japanese_learning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:hungvu140804@gmail.com}
    password: ${MAIL_PASSWORD:yawbarvdqelbbmxb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 165606726136-heuroqd4d8gfes6u7s9l2vr4oome5ov0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/api/login/oauth2/code/google"
            scope:
              - email
              - profile

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO
